# ==========================================================

# Circuit Breaker для интеграции с ФТ

# ==========================================================

# Тип окна статистики:
# COUNT_BASED - анализируем фиксированное количество последних вызовов
resilience4j.circuitbreaker.instances.deposit-fns-circuit-breaker.sliding-window-type=COUNT_BASED

# Размер окна статистики. Храним информацию только о последних 10 вызовах.
resilience4j.circuitbreaker.instances.deposit-fns-circuit-breaker.sliding-window-size=10

# Минимальное количество вызовов для начала анализа. Пока не накопится 4 вызова, CircuitBreaker не будет рассчитывать процент ошибок.
resilience4j.circuitbreaker.instances.deposit-fns-circuit-breaker.minimum-number-of-calls=4

# Порог процента ошибок. Если количество ошибок достигнет 70% и более, CircuitBreaker перейдет в состояние OPEN.
resilience4j.circuitbreaker.instances.deposit-fns-circuit-breaker.failure-rate-threshold=70

# Время нахождения в состоянии OPEN. В течение 30 секунд все вызовы будут блокироваться.
resilience4j.circuitbreaker.instances.deposit-fns-circuit-breaker.wait-duration-in-open-state=30s

# Количество тестовых вызовов в состоянии HALF_OPEN. После OPEN будут разрешены только 3 проверочных запроса.
resilience4j.circuitbreaker.instances.deposit-fns-circuit-breaker.permitted-number-of-calls-in-half-open-state=3

# Максимальное время нахождения в HALF_OPEN. Если за 10 секунд не наберется 3 тестовых вызова, CircuitBreaker автоматически вернется в OPEN.
resilience4j.circuitbreaker.instances.deposit-fns-circuit-breaker.max-wait-duration-in-half-open-state=10s

# Автоматический переход OPEN -> HALF_OPEN через wait-duration-in-open-state.
resilience4j.circuitbreaker.instances.deposit-fns-circuit-breaker.automatic-transition-from-open-to-half-open-enabled=true
