spring:
  application:
    name: FintenderStabilityBreaker


resilience4j:
  ratelimiter:
    instances:
      deposit-recheck-fns:
        limitForPeriod: 50         # Максимум 50 запросов к сервису ФТ за один период.
        limitRefreshPeriod: 1m     # Период обновления лимита. Каждую минуту счетчик разрешений сбрасывается и снова становится доступно 50 запросов.
        timeoutDuration: 5m        # Максимальное время ожидания свободного permit. Если лимит исчерпан, поток будет ожидать до 5 минут.